### ISSUE TITLE
Add CRD to create secrets wrapper

### ISSUE THREAD

**Issue by omerlh** [Soluto/kamus#13]
Many existing applications running on Kubernetes relays on secrets to store sensitive data - which make Kamus unusable. This can be solved with a CRD that is wrapper around secret, something in the following format:
```
apiVersion: v1
kind: KamusSecret
metadata:
  name: mysecret
  namespace: default
  service-account: default
type: Opaque
data:
  username: <encrypted data>
  password: <encrypted data>
```
The CRD controller will use Kamus and the SA token to decrypt the value of the secret and create a real Kubernetes secret object from it.
