### ISSUE TITLE
Faling to decrypt KamusSecret

### ISSUE THREAD

**Issue by DannyeB** [Soluto/kamus#290]
**General remarks**
My understanding of the KamusSecrets is that when you create one the Kamus controller decrypts the values. Then it base64's the values and creates a regular k8s secret. 

**Describe the bug**
When I create a KamusSecret from a file it creates a new secret but the values are kamus encrypted not base64'd. I can see the following logs from the KamusController:
```javascript
{"Timestamp":"2019-08-21T09:51:28.4392305+00:00","Level":"Information","MessageTemplate":"Handling event of type {type}. KamusSecret {name} in namespace {namespace}","Properties":{"type":"Deleted","name":"argocd-secret","namespace":"argocd","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
{"Timestamp":"2019-08-21T09:51:28.5406336+00:00","Level":"Error","MessageTemplate":"Error while handling KamusSecret event of type {eventType}, for KamusSecret {name} on namespace {namespace}","Exception":"Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NotFound'\n   at k8s.Kubernetes.DeleteNamespacedSecretWithHttpMessagesAsync(String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)\n   at k8s.KubernetesExtensions.DeleteNamespacedSecretAsync(IKubernetes operations, String name, String namespaceParameter, V1DeleteOptions body, String dryRun, Nullable`1 gracePeriodSeconds, Nullable`1 orphanDependents, String propagationPolicy, String pretty, CancellationToken cancellationToken)\n   at CustomResourceDescriptorController.HostedServices.V1AlphaController.HandleDelete(KamusSecret kamusSecret) in /app/crd-controller/HostedServices/V1AlphaController.cs:line 200\n   at CustomResourceDescriptorController.HostedServices.V1AlphaController.HandleEvent(WatchEventType event, KamusSecret kamusSecret) in /app/crd-controller/HostedServices/V1AlphaController.cs:line 96","Properties":{"eventType":"Deleted","name":"argocd-secret","namespace":"argocd","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
{"Timestamp":"2019-08-21T09:51:57.0634900+00:00","Level":"Information","MessageTemplate":"Handling event of type {type}. KamusSecret {name} in namespace {namespace}","Properties":{"type":"Added","name":"argocd-secret","namespace":"argocd","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
{"Timestamp":"2019-08-21T09:51:57.0818170+00:00","Level":"Error","MessageTemplate":"Failed to decrypt KamusSecret key {key}. KamusSecret {name} in namespace {namespace}","Exception":"System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.\n   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)\n   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n   at Kamus.KeyManagement.RijndaelUtils.Decrypt(Byte[] key, Byte[] iv, Byte[] encryptedData) in /app/key-managment/RijndaelUtils.cs:line 54\n   at Kamus.KeyManagement.SymmetricKeyManagement.Decrypt(String encryptedData, String serviceAccountId) in /app/key-managment/SymmetricKeyManagement.cs:line 27\n   at CustomResourceDescriptorController.HostedServices.V1AlphaController.CreateSecret(KamusSecret kamusSecret) in /app/crd-controller/HostedServices/V1AlphaController.cs:line 138","Properties":{"key":"github.clientid","name":"argocd-secret","namespace":"argocd","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
{"Timestamp":"2019-08-21T09:51:57.0827066+00:00","Level":"Error","MessageTemplate":"Failed to decrypt KamusSecret key {key}. KamusSecret {name} in namespace {namespace}","Exception":"System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.\n   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)\n   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n   at Kamus.KeyManagement.RijndaelUtils.Decrypt(Byte[] key, Byte[] iv, Byte[] encryptedData) in /app/key-managment/RijndaelUtils.cs:line 54\n   at Kamus.KeyManagement.SymmetricKeyManagement.Decrypt(String encryptedData, String serviceAccountId) in /app/key-managment/SymmetricKeyManagement.cs:line 27\n   at CustomResourceDescriptorController.HostedServices.V1AlphaController.CreateSecret(KamusSecret kamusSecret) in /app/crd-controller/HostedServices/V1AlphaController.cs:line 138","Properties":{"key":"github.repo.password","name":"argocd-secret","namespace":"argocd","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
{"Timestamp":"2019-08-21T09:51:57.0832770+00:00","Level":"Error","MessageTemplate":"Failed to decrypt KamusSecret key {key}. KamusSecret {name} in namespace {namespace}","Exception":"System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.\n   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)\n   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n   at Kamus.KeyManagement.RijndaelUtils.Decrypt(Byte[] key, Byte[] iv, Byte[] encryptedData) in /app/key-managment/RijndaelUtils.cs:line 54\n   at Kamus.KeyManagement.SymmetricKeyManagement.Decrypt(String encryptedData, String serviceAccountId) in /app/key-managment/SymmetricKeyManagement.cs:line 27\n   at CustomResourceDescriptorController.HostedServices.V1AlphaController.CreateSecret(KamusSecret kamusSecret) in /app/crd-controller/HostedServices/V1AlphaController.cs:line 138","Properties":{"key":"github.repo.user","name":"argocd-secret","namespace":"argocd","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
{"Timestamp":"2019-08-21T09:51:57.0838982+00:00","Level":"Error","MessageTemplate":"Failed to decrypt KamusSecret key {key}. KamusSecret {name} in namespace {namespace}","Exception":"System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.\n   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)\n   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n   at Kamus.KeyManagement.RijndaelUtils.Decrypt(Byte[] key, Byte[] iv, Byte[] encryptedData) in /app/key-managment/RijndaelUtils.cs:line 54\n   at Kamus.KeyManagement.SymmetricKeyManagement.Decrypt(String encryptedData, String serviceAccountId) in /app/key-managment/SymmetricKeyManagement.cs:line 27\n   at CustomResourceDescriptorController.HostedServices.V1AlphaController.CreateSecret(KamusSecret kamusSecret) in /app/crd-controller/HostedServices/V1AlphaController.cs:line 138","Properties":{"key":"github.secret","name":"argocd-secret","namespace":"argocd","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
{"Timestamp":"2019-08-21T09:51:57.0844838+00:00","Level":"Error","MessageTemplate":"Failed to decrypt KamusSecret key {key}. KamusSecret {name} in namespace {namespace}","Exception":"System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.\n   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)\n   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n   at Kamus.KeyManagement.RijndaelUtils.Decrypt(Byte[] key, Byte[] iv, Byte[] encryptedData) in /app/key-managment/RijndaelUtils.cs:line 54\n   at Kamus.KeyManagement.SymmetricKeyManagement.Decrypt(String encryptedData, String serviceAccountId) in /app/key-managment/SymmetricKeyManagement.cs:line 27\n   at CustomResourceDescriptorController.HostedServices.V1AlphaController.CreateSecret(KamusSecret kamusSecret) in /app/crd-controller/HostedServices/V1AlphaController.cs:line 138","Properties":{"key":"tls.crt","name":"argocd-secret","namespace":"argocd","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
{"Timestamp":"2019-08-21T09:51:57.0850339+00:00","Level":"Error","MessageTemplate":"Failed to decrypt KamusSecret key {key}. KamusSecret {name} in namespace {namespace}","Exception":"System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.\n   at Internal.Cryptography.UniversalCryptoDecryptor.DepadBlock(Byte[] block, Int32 offset, Int32 count)\n   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)\n   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()\n   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n   at Kamus.KeyManagement.RijndaelUtils.Decrypt(Byte[] key, Byte[] iv, Byte[] encryptedData) in /app/key-managment/RijndaelUtils.cs:line 54\n   at Kamus.KeyManagement.SymmetricKeyManagement.Decrypt(String encryptedData, String serviceAccountId) in /app/key-managment/SymmetricKeyManagement.cs:line 27\n   at CustomResourceDescriptorController.HostedServices.V1AlphaController.CreateSecret(KamusSecret kamusSecret) in /app/crd-controller/HostedServices/V1AlphaController.cs:line 138","Properties":{"key":"tls.key","name":"argocd-secret","namespace":"argocd","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
{"Timestamp":"2019-08-21T09:51:57.1204647+00:00","Level":"Information","MessageTemplate":"Created a secret from KamusSecret {name} in namespace {namespace} successfully.","Properties":{"name":"argocd-secret","namespace":"argocd","log_type":"audit","SourceContext":"CustomResourceDescriptorController.HostedServices.V1AlphaController"}}
```

**Versions used**
Kamus (API images): 
 - soluto/kamus:controller-0.4.4.1
 - soluto/kamus:decryptor-0.4.4.1
 - soluto/kamus:encryptor-0.4.4.1
Kamus CLI: 0.2.3
Chart version: latest pulled with `helm fetch soluto/kamus` pulled 21st August 2019
KMS provider: AES
Kubernetes flavour and version: IBM Kubernetes Service(IKS) v1.15.2+IKS

**To Reproduce**
1. Apply the secret
```YAML
apiVersion: "soluto.com/v1alpha1"
kind: KamusSecret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
serviceAccount: argocd
data:
  tls.crt: "Fov7DL8jWcXW3z4yNB9TjQ==:+IO+xRzbOj+hoIcSbU85BG7BZnnmMrlbAPv8CQ+QnOBwcdydYdub6WQR26EdkbDWG4nOzD/WB3NAqEodlu2udrMFAIbvQrI3VIsrb5dSTqHrcdeVtvG+PnZe31a1rZrGjkhgcUqsXMuJhoHGwygEo8dc9k8Zp1GgtWiywuBmwJ05KlFFvkKywBVsptGZfJWsDzrL+z+XS+vpfAzJVbT9/mNXi3MUG46usDzbCfOBvPbhXwB3FA9sGTNojQ1HMuKqxYtbc45KLrqTeNF4CJMnJnn7P1CDL/Fr9wGQksVt5wKGLGVXOzg/Pq+OVZbzq+ZhCWSwU+M/0XPvB93b8WO0PeTsTY8kzBAUcr2mocqnchsBc5WwtXcSRrElCX/KqY72MA5k9LU2otN+8PqfC++lX3C0+SOdp+8Y0lOHvMe9zA=="
  tls.key: "Lo85AmgCxZoYXSrP6d/scQ==:8gZitSXCkDbumbhVKk+DlEfeiOq4JCoWCq+yw4R7u2btH7U05uslaFGfL40TvM2HswaR/rI66RzgZqFgrIakxW77eYZb2bycu6MUaKoM7KPTAhzrFMdlEVud6wxVZZxFyQb84pb0xzxTAE4aea67R0RvFzFHgKhwEvrSXj2GmzRx/xX21K6NxaxxPyYk1gDbJlgP9sqC4S1Bn0IZylZ6oQ0AaSjiMyY/j7SGWq1mKML1MliyAaz/a92jws/Lb4GdgSyAkcWPmQuz3xW4aYclkHwl8/AR1LOzQHS9T/w834P68naQI+Beb0inetE3EnlEVMT5mxrqSvtoHnqm/7lDHu4gWsj/IVXhLUOCpUdOYq4VCUuKq7PFrvVfmXtOIK04IQ2XR39aPybRo/Bob75U8XyDdbLuXseIip0cvQXoffvLBB5BHQ6a+3O0hVqZ90u0s8KBs5q9VCDmnh4hDdXkPOBkmXGz4URHL3qWKBedZf7b1LagSWLDWx0oYW0x25C22xIVRcSMcSoSlXXIZv+nEJhFv1WCGZEgwopasg50omULP"
  github.clientid: "G4KrwbeXhejbRBBGsORGCQ==:GmwzwmafZUQ5w44fh8KR+9iWmubuYtgpB+eI="
  github.secret: "bt/cu/a/JYrUteXngZMsjA==:l4LHnaUh28AVivT3xakJ5GHkdN4Jw7jb/r8Pngwq/TW3MU5SYTEZXv5Lt"
  github.repo.user: "9Flp0qrpQ+Q==:BiKfWt1I96mwAHRWeaq/aA=="
  github.repo.password: "nvGzqxT1Gmtvz1cMzZB8Sg==:AyH4dfz+c3C8IJYVvDkGphdR77IBMuklT41HFRwKLUIxiLp8wM"
```
2. Observe secret created but values are KamusEncrypted

**Expected behavior**
Expected to see a new k8s secret created with the values being decrypted and base64'd 

[Kamus slack]: (https://join.slack.com/t/k8s-kamus/shared_invite/enQtNTQwMjc2MzIxMTM3LTgyYTcwMTUxZjJhN2JiMTljMjNmOTBmYjEyNWNmZTRiNjVhNTUyYjMwZDQ0YWQ3Y2FmMTBlODA5MzFlYjYyNWE)
