### ISSUE TITLE
Getting Error "Undefined" on Kamus Encrypt

### ISSUE THREAD

**Issue by MystiqueRose** [Soluto/kamus#413]
**Describe the bug**
I have configured service principal in Azure and also the respective key vault with a secret name token. I'm using AD so, I'm trying to encrypt using the following flags:

```
kamus-cli encrypt \
    --auth-tenant <tenant_uuid> \
    --auth-resource <resource_uuid> \
    --auth-application <application_uuid> \
    --secret token \
    --service-account kamus-admin \
    --namespace ingest \
    --kamus-url <my_url> \
    --allow-insecure-url

```
My kamus deployment yaml is:

```
keyManagement:
  provider: AzureKeyVault
  azureKeyVault:
    clientId: <client_id_uuid>
    clientSecret: <client_secret>
    keyVaultName: <azure_key_vault_name>
    keyType: RSA
    keySize: 2048
    maximumDataLength: 214

```
My app auth configuration is like:

![image](https://user-images.githubusercontent.com/5752362/72756719-db6d2b80-3bac-11ea-91a4-16347c54daec.png)

My secret is an 16 bytes key

Kamus cli logs:

[info  kamus-cli]: Encryption started...
[info  kamus-cli]: service account: kamus-admin
[info  kamus-cli]: namespace: ingest
[info  kamus-cli]: Open "https://microsoft.com/devicelogin" in browser and login to Azure with the following code: EAZGJ86ED
**[error kamus-cli]: Error while trying to encrypt with kamus: undefined**

I don't know how to debug this exception, container just prints undefined.

**Versions used**
Kamus (API images): 0.5.2.0
Kamus CLI: 0.2.3
Chart version: kamus-0.4.3
KMS provider: Azure Key Vault
Kubernetes flavour and version: 1.14.9-gke.2

**To Reproduce**
1. Install kamus on k8s
2. Configure service principal
3. Execute kamus cli with flags showed above

**Expected behavior**
A clear exception message from kamus cli.

[Kamus slack]: (https://join.slack.com/t/k8s-kamus/shared_invite/enQtODA2MjI3MjAzMjA1LThlODkxNTg3ZGVmMjVkOTBhY2RmMmRjOWFiOGU2NzQ1ODU4ODNiMDJiZTE5ZTY4YmRiOTM3MjI0MDc0OGFkN2E)
